<a href="https://colab.research.google.com/github/gleonmen/spark-week/blob/master/Numpy_Excercises_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy Excercises - Session 2

### Exercise 1

Reshape `array1` to 7x3 dimensions.

In [2]:
array1 = np.arange(0, 21)
array1 = np.reshape(array1,(7,3))
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

### Exercise 2

Reshape `array2` into a 3D array of 3x3x3 dimensions.

In [8]:
array2 = np.arange(0, 27).reshape(9, 3)
array2
array2 = np.reshape(array2,(3,3,3))
array2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Exercise 3: Reshape vs Resize

reshape and resize both do the same thin. So, what's the difference?

Follow the instructions and find out.


In [11]:
# Run this cell without changing the code.
array3 = np.arange(0, 9)

array3.reshape((3, 3))
print(array3)

array3.resize((3, 3))
print(array3)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question: What is the difference between reshape and resize

a = "resize returns a new copy of the array, while reshape changes the original array"
b = "reshape returns a new copy of the array, while resize changes the original array"
c = "both resize and reshape works in the same way with the original array"
#test3()

### Exercise 4

Concatenate arrays `a`, `b`, and `c`.

In [13]:
a = np.arange(0, 3)
b = np.arange(3, 6)
c = np.arange(6, 9)
array4 = np.concatenate((a,b,c))
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 5

Concatenate arrays `m1` and `m2` vertically.

In [14]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array5 = np.concatenate((m1,m2)) 
array5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Exercise 6

Concatenate arrays `m1` and `m2` horizontally.

In [16]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array6 = np.concatenate((m1,m2),axis=1)
array6

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### Exercise 7

Get all the cells with value equals to `0` as a list of tuples.


In [133]:
matrix = np.array([
    [1, 4, 7, 5, 0],
    [0, 2, 9, 0, 1],
    [3, 6, 0, 5, 3],
    [7, 3, 0, 1, 0],
    [3, 6, 1, 0, 4]
])
print(matrix)
zeroTuples = np.where(matrix==0)
list1 = zeroTuples[0]
list2 = zeroTuples[1]
print(list1)
print(list2)
merged_list = [(list1[i], list2[i]) for i in range(0, len(list1))] 
merged_list2 = (list1,list2)
print(merged_list)
#print(merged_list2)
#merged_list = [(list1[i], list2[i]) for i in range(0, len(list1))] 
#arrayConcat = np.asmatrix(zeroTuples)
#print(arrayConcat)
#tr = np.transpose(arrayConcat)
#print(tr)
#print(np.asarray(tr))
#print(lst)

 #   return tuple(a)
#tuples = (zeroTuples[0], zeroTuples[1])
#print(tuples)
#print(tupples)
#array7 = 
#test5(array7)

[[1 4 7 5 0]
 [0 2 9 0 1]
 [3 6 0 5 3]
 [7 3 0 1 0]
 [3 6 1 0 4]]
[0 1 1 2 3 3 4]
[4 0 3 2 2 4 3]
[(0, 4), (1, 0), (1, 3), (2, 2), (3, 2), (3, 4), (4, 3)]
(array([0, 1, 1, 2, 3, 3, 4]), array([4, 0, 3, 2, 2, 4, 3]))


### Exercise 8

Check the documentation for `np.diag` and `np.fliplr`. Use them to extract the diagonals arrays for `matrix`.



In [117]:
diag1 = np.diag(matrix)
print(diag1)
matrix2 = np.fliplr(matrix) 
print(matrix2)
diag2 = np.diag(matrix2)
print(diag2)
#testDiag1(diag1)
#testDiag2(diag2)

[1 2 0 1 4]
[[0 5 7 4 1]
 [1 0 9 2 0]
 [3 5 0 6 3]
 [0 1 0 3 7]
 [4 0 1 6 3]]
[0 0 0 3 3]


### Exercise 9

Get the values of the 3th column in `matrix` and the values for the 2th row in `matrix`. Both as numpy arrays.


In [134]:

column = np.asarray(matrix[:,2])
print(column)
row = np.asarray(matrix[1,:]) 
print(row)
#testRow(row)

[7 9 0 0 1]
[0 2 9 0 1]


## Exercise 10

Create a new matrix ***x*** from ***a*** and ***m*** with the folowing structure:



```
array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])
```



In [146]:
a = np.full((3, 1), 5)
m = np.full((3, 4), 4)
print(a)
print(m)
arrays = np.hsplit(m,2)
print(arrays)
side1 = arrays[0]
side2 = arrays[1]
print(side1)
step1 = np.concatenate((side1,a,side2),axis=1)
print(step1)


[[5]
 [5]
 [5]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[array([[4, 4],
       [4, 4],
       [4, 4]]), array([[4, 4],
       [4, 4],
       [4, 4]])]
[[4 4]
 [4 4]
 [4 4]]
[[4 4 5 4 4]
 [4 4 5 4 4]
 [4 4 5 4 4]]


## Exercise 11

Given a:

```
a = array([[1],
       [1],
       [2],
       [4]])
```

Create a new array **b** with the following structure:

```
np.array([
  [1, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])
```
Do you detect the pattern? Which operation do you need to create this structure.?




In [147]:
# one hot encode excersise for numpy 

# Challenge, Tic Tac Toe


In [155]:
cell = {
    0: ' ',
    1: 'X',
    2: 'O'
}

def print_board():
  print('-------------')
  print(f'| {cell[game[0][0]]} | {cell[game[0][1]]} | {cell[game[0][2]]} |')
  print('-------------')
  print(f'| {cell[game[1][0]]} | {cell[game[1][1]]} | {cell[game[1][2]]} |')
  print('-------------')
  print(f'| {cell[game[2][0]]} | {cell[game[2][1]]} | {cell[game[2][2]]} |')
  print('-------------')

def skynet_move():
  # Select a random empty cell in `game` array and set with value `2`.
  # If no empty cells available, do nothing.
  pass

def win_move(player, r, c):
  # Check if the player's move is a win move.
  # A win move meets one of these conditions:
  #   - All values at row `r` are equal to `player`.
  #   - All values at column `c` are equal to `player`.
  #   - All values at main diagonal ((0, 0) to (2, 2)) are equal to  `player`.
  #   - All values at second diagonal ((2, 0) to (0, 2)) are equal to  `player`.
  # Return True if one of the conditions are met, False otherwise.

    pass


def human_move(r, c):
  id 
  # Set value `1` at game[r][c] if the cell if empty and return True.
  # If cell is not empty print "Cell is not empty" and return False.
  pass

def winner_exists():
  # If one of the players has already won the game, return True.
  # Return False otherwise.
  pass


def is_game_on():
  # This method checks the current status of the game.
  # A game is on if meets one of two conditios:
  #  - There is still available cells.
  #  - There is still no winners.  
  pass

In [154]:
# Run this cell to restart the game.

# Create a 3x3 array with zero values.
game = np.full((3,3),0)

In [ ]:
#@title Tic tac toe controls
#@markdown Select the cell for your next move!.
row_value = "2" #@param ["0", "1", "2"] 
column_value = "2" #@param ["0", "1", "2"]

row = int(row_value)
column = int(column_value)
if(is_game_on()):
  status = human_move(row, column)
  if(win_move(1, row, column)):
    print('Human wins')
  elif(status):
    skynet_move()
    if(win_move(2, row, column)):
      print('Skynet wins')
else:
  print('Game over.')
  
print_board()

# Challenge: Basic data analysis

The following numpy array is taken from the a census dataset. Every column in this matrix contains some demografic information. For this exercise You will focus in the following columns:

*   Column[0]: Age
*   Column[1]: workclass
*   Column[3]: education
*   Column[5]: marital-status
*   Column[9]: sex
*   Column[10]: capital-gain

Please find the following information:


*   Age average
*   Types of workclass, education and marital-status
*   How many records are for male
*   How many records are for female
*   How many females are above age of 30
*   Avergage of capital-gain for males
*   Avergage of capital-gain for females







In [ ]:
# First upload file "census.npy" befor running this cell.
with open('census.npy', 'rb') as f:
  census_data = np.load(f, allow_pickle=True)
census_data

array([[50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)